[build]
publish = "public"
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL/dev-guide --config=dev-guide.toml ; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL/extension-dev-guide --config=extension-dev-guide.toml"

[context.production]
command = "hugo --gc --minify --buildFuture -b $URL/dev-guide --config=dev-guide.toml ; hugo --gc --minify --buildFuture -b $URL/extension-dev-guide --config=extension-dev-guide.toml"
  [context.production.environment]
  HUGO_VERSION = "0.97.2"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL/dev-guide --config=dev-guide.toml ; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL/extension-dev-guide --config=extension-dev-guide.toml"
  [context.deploy-preview.environment]
  HUGO_VERSION = "0.97.2"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/extension-dev-guide"
  status = 301
  force = false